/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imcalculator;

/**
 *
 * @author Gonzalo
 */
public class IMCMenu extends javax.swing.JFrame {

    /**
     * Creates new form IMCMenu
     */
    public IMCMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        lblCM = new javax.swing.JLabel();
        lblComposition = new javax.swing.JLabel();
        lblKG = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblHeight1 = new javax.swing.JLabel();
        lblIMCr = new javax.swing.JLabel();
        lblIMC1 = new javax.swing.JLabel();
        lblComposition1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(840, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("IMC Calculator");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 110));

        txtHeight.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtHeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHeight.setText("0");
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        getContentPane().add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 240, -1));

        txtWeight.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtWeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtWeight.setText("0");
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        getContentPane().add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 240, -1));

        lblCM.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCM.setText("CM");
        getContentPane().add(lblCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 70, 40));

        lblComposition.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblComposition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComposition.setText("N/A");
        getContentPane().add(lblComposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 240, 40));

        lblKG.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblKG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKG.setText("KG");
        getContentPane().add(lblKG, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 70, 40));

        lblWeight.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWeight.setText("Weight");
        getContentPane().add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 120, 40));

        lblHeight1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblHeight1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeight1.setText("Height");
        getContentPane().add(lblHeight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 40));

        lblIMCr.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblIMCr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIMCr.setText("0");
        getContentPane().add(lblIMCr, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 120, 40));

        lblIMC1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblIMC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIMC1.setText("IMC");
        getContentPane().add(lblIMC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 40));

        lblComposition1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblComposition1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComposition1.setText("Body Composition:");
        getContentPane().add(lblComposition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 240, 40));

        btnExit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 260, 60));

        btnCalculate.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 260, 60));

        btnClear.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 260, 60));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imcalculator/resources/images/body.png"))); // NOI18N
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 230, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        
        Parameters Person;
        
        Person = new Parameters();
        
        Person.setHeight(Integer.parseInt(txtHeight.getText()));
        Person.setWeight(Float.parseFloat(txtWeight.getText()));
        
        lblIMCr.setText(String.valueOf(Person.GetIMC()));
        lblComposition.setText(String.valueOf(Person.getComposition()));
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtHeight.setText("0");
        txtWeight.setText("0");
        lblIMCr.setText("0");
        lblComposition.setText("N/A"); 
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMCMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMCMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMCMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMCMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMCMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblCM;
    private javax.swing.JLabel lblComposition;
    private javax.swing.JLabel lblComposition1;
    private javax.swing.JLabel lblHeight1;
    private javax.swing.JLabel lblIMC1;
    private javax.swing.JLabel lblIMCr;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblKG;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
